# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('poster_url', models.CharField(max_length=1000)),
                ('release_year', models.IntegerField(max_length=4)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField(max_length=5)),
                ('imdb_link', models.CharField(max_length=1000)),
                ('cast', models.CharField(max_length=1000)),
            ],
        ),
    ]
