# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_input', models.CharField(max_length=5000)),
                ('movie_year', models.IntegerField(default=2017)),
                ('rating', models.FloatField(default=4)),
                ('feelings', models.CharField(max_length=500)),
                ('recommended_movies', models.CharField(max_length=1000)),
            ],
        ),
    ]
