# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefy_lstm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lstm',
            old_name='movie_year',
            new_name='end_year',
        ),
        migrations.RemoveField(
            model_name='lstm',
            name='feelings',
        ),
        migrations.RemoveField(
            model_name='lstm',
            name='recommended_movies',
        ),
        migrations.AddField(
            model_name='lstm',
            name='start_year',
            field=models.IntegerField(default=2010),
        ),
        migrations.AlterField(
            model_name='lstm',
            name='rating',
            field=models.FloatField(default=7),
        ),
    ]
